# Generated by Django 2.2.5 on 2019-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
