# Generated by Django 2.2.5 on 2019-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0002_auto_20191017_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
