# Generated by Django 2.2.5 on 2019-10-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0003_auto_20191017_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='condition',
        ),
        migrations.AddField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mng.task'),
        ),
    ]
