# Generated by Django 2.2.5 on 2019-10-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0004_auto_20191018_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='condition',
            field=models.IntegerField(choices=[(1, '未着手'), (2, '未完了'), (3, '完了')], null=True),
        ),
    ]
