# Generated by Django 2.2.5 on 2019-10-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0005_task_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='level',
            new_name='progress',
        ),
        migrations.AlterField(
            model_name='progress',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mng.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.IntegerField(blank=True, choices=[(1, '未着手'), (2, '未完了'), (3, '完了')], null=True),
        ),
    ]
